### ISSUE TITLE
RTB Files

### ISSUE THREAD

**Issue by renatocosta** [ddd-crew/virtual-modelling-templates#3]
Hi,

I would like to praise them for making the templates available.
But I am not a premium member on Miro.
Can I have all of them by sharing with my account renatocostahome@gmail.com ?

Best Regards

**Comment by yellowbrickc** [comment]
I wasn't aware of this, but you are right, one must have at least a team plan to be able to use them 😞 
The same situation is valid for all of us, I'm afraid.

Maybe would these templates give some motivation at your company to think about a Miro Team plan?
@NTCoding what do you think?

**Comment by renatocosta** [comment]
Thank you @yellowbrickc for letting me know.
For sure, all of templates is to be used in.
From templates I can see a lot of opportunities to empower my company to deal with DDD.
For now my company has no money to upgrade.

Tks

**Comment by yellowbrickc** [comment]
I can understand this very well. Let's see if @NTCoding has an idea.

**Comment by NTCoding** [comment]
It's on my todo list to create templates in Miroverse. Miro emailled me but I'm quite busy at the  moment with other things. I'll try and get it on Miro before I go on holiday though.

Thanks for your patience.

**Comment by yellowbrickc** [comment]
You are a crazy guy!!!

**Comment by NTCoding** [comment]
Live on the Miroverse https://miro.com/miroverse/category/strategy-and-planning/strategic-domain-driven-design-template
